package sdm.android.thesaurus.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class RelatedWord  {

    private Object rgPartOfSpeech;  // q
    private Object rgOrder;  // q
    private Object rgwId;  // q
    private Object rgId;  // q
    private Object rgwWord;  // q
    private Object rgwNote;  // q
    private Object rgwOrder;  // q

    public Object getRgPartOfSpeech() {
        return this.rgPartOfSpeech;
    }

    public void setRgPartOfSpeech(Object rgPartOfSpeech) {
        this.rgPartOfSpeech = rgPartOfSpeech;
    }

    public Object getRgOrder() {
        return this.rgOrder;
    }

    public void setRgOrder(Object rgOrder) {
        this.rgOrder = rgOrder;
    }

    public Object getRgwId() {
        return this.rgwId;
    }

    public void setRgwId(Object rgwId) {
        this.rgwId = rgwId;
    }

    public Object getRgId() {
        return this.rgId;
    }

    public void setRgId(Object rgId) {
        this.rgId = rgId;
    }

    public Object getRgwWord() {
        return this.rgwWord;
    }

    public void setRgwWord(Object rgwWord) {
        this.rgwWord = rgwWord;
    }

    public Object getRgwNote() {
        return this.rgwNote;
    }

    public void setRgwNote(Object rgwNote) {
        this.rgwNote = rgwNote;
    }

    public Object getRgwOrder() {
        return this.rgwOrder;
    }

    public void setRgwOrder(Object rgwOrder) {
        this.rgwOrder = rgwOrder;
    }
}