package sdm.android.thesaurus.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Word  {

    private Long wId;  // t
    private String wWord;  // t

    public Long getWId() {
        return this.wId;
    }

    public void setWId(Long wId) {
        this.wId = wId;
    }

    public String getWWord() {
        return this.wWord;
    }

    public void setWWord(String wWord) {
        this.wWord = wWord;
    }
}